require 'docx/xml/generic'
require 'docx/xml/run_properties'
require 'docx/xml/numbering_properties'
require 'docx/xml/paragraph_properties'
require 'docx/xml/drawing'
require 'docx/xml/run'
require 'docx/xml/paragraph'
require 'docx/xml/document'
